-- day wise and commutative revenue generated by the shop

SELECT payment_date, amount, sum(amount) OVER (ORDER BY payment_date) as commutative_amount
FROM (
  SELECT CAST(payment_date AS DATE) AS payment_date, SUM(amount) AS amount
  FROM "DBT_DEMO_SOURCES"."RAW"."PAYMENT"
  GROUP BY CAST(payment_date AS DATE)
) p
ORDER BY payment_date